### ISSUE TITLE
Reason behind tools failing update tests?

### ISSUE THREAD

**Issue by wm75** [usegalaxy-au/usegalaxy-au-tools#779]
I've noticed that new versions of several iuc tools I'm interested in (pangolin, ivar, lofreq, ...) are consistently failing the tests during automated AU tool updates and then do not get installed.
What are the reasons behind these failures? The logs aren't public, are they?

**Comment by cat-bro** [comment]
Hi @wm75 , each tool is installed, then there is 90s of sleep before tests are run. Usually this is enough but lately some tools have been failing because at some point in the test process they get a job handler that is not aware that the tool is installed. We're going to retry yesterday's updates with a longer pause between installing and testing to see if that helps.

**Comment by cat-bro** [comment]
Closing this issue because the updates in question have been installed.
